name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        
    - name: Debug environment
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Package.json exists: $(test -f package.json && echo 'yes' || echo 'no')"
        echo "Package-lock.json exists: $(test -f package-lock.json && echo 'yes' || echo 'no')"
        
    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed successfully!"
        echo "Checking dist directory:"
        ls -la dist/ || echo "No dist directory found"
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        
    - name: Deploy to Vercel (Production)
      if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && secrets.VERCEL_TOKEN != ''
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        
    - name: Deploy to Vercel (Preview)
      if: (github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master') && secrets.VERCEL_TOKEN != ''
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--no-wait'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        
    - name: Build completed successfully
      if: secrets.VERCEL_TOKEN == ''
      run: |
        echo "✅ Build completed successfully!"
        echo "ℹ️  Vercel deployment skipped - VERCEL_TOKEN secret not configured"
        echo "📦 Built files are ready in the 'dist' directory"
        
    - name: Comment PR with deployment URL
      if: github.event_name == 'pull_request' && secrets.VERCEL_TOKEN != ''
      uses: actions/github-script@v7
      with:
        script: |
          const { data: deployments } = await github.rest.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const latestDeployment = deployments[0];
          if (latestDeployment) {
            const deploymentUrl = `https://${latestDeployment.environment}.vercel.app`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Deployment Ready!**
              \n\n📱 **URL:** ${deploymentUrl}
              \n\nThis preview will be automatically updated when you push new commits to this PR.`
            });
          }
          
    - name: Comment PR with build status
      if: github.event_name == 'pull_request' && secrets.VERCEL_TOKEN == ''
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✅ **Build Completed Successfully!**
            \n\n📦 The application has been built and is ready for deployment.
            \n\nℹ️ Vercel deployment is not configured for this repository. To enable automatic deployments, add the following secrets to your repository:
            \n- \`VERCEL_TOKEN\`
            \n- \`VERCEL_ORG_ID\`
            \n- \`VERCEL_PROJECT_ID\``
          });
